services:
  schemaspy:
    image: schemaspy/schemaspy:6.1.0
    volumes:
      - ./schema:/output
      - ./docker/schemaspy/drivers:/drivers
      - ./docker/schemaspy/schemaspy.properties:/schemaspy.properties
    depends_on:
      - database
