version: "3"
services:
  php:
    user: www-data
    build:
      context: ./docker/php
    depends_on:
      - database
      - mail
    ports:
      - ${PORT_WEB_APP:-8000}:8000
      - ${PORT_BROWSERSYNC:-3000}:${PORT_BROWSERSYNC:-3000}
    volumes:
      - php:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/httpd.conf:/etc/apache2/apache2.conf
    working_dir: /var/www
    environment:
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_KEY: _DUMMYDUMMYDUMMYDUMMYDUMMYDUMMY_
      APP_ENV: local
      APP_URL: http://localhost:8000
      APP_TIMEZONE: Asia/Tokyo
      APP_LOCALE: ja
      APP_FAKER_LOCALE: ja_JP
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      PGHOST: database
      PGUSER: postgres
      TZ: Asia/Tokyo
      MAIL_MAILER: smtp
      MAIL_HOST: mail
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: "null"
      QUEUE_CONNECTION: sync
      LANG: C.UTF-8
      LANGUAGE: en_US

  database:
    image: postgres:bullseye
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - ${PORT_PGSQL:-0}:5432
    environment:
      TZ: Asia/Tokyo
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  mail:
    image: axllent/mailpit
    ports:
      - ${PORT_WEB_MAIL:-8025}:8025

volumes:
  database:
  php:
