services:
  php:
    user: www-data
    build:
      context: ./docker/php
    depends_on:
      - database
      - mail
    ports:
      - ${PORT_WEB_APP:-8000}:8000
      - ${PORT_BROWSERSYNC:-3000}:${PORT_BROWSERSYNC:-3000}
    volumes:
      - php:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/httpd.conf:/etc/apache2/apache2.conf
      - ./docker/php/my.cnf:/home/www-data/.my.cnf
    working_dir: /var/www
    environment:
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_KEY: _DUMMYDUMMYDUMMYDUMMYDUMMYDUMMY_
      APP_ENV: local
      APP_URL: http://localhost:8000
      APP_TIMEZONE: Asia/Tokyo
      APP_LOCALE: ja
      APP_FAKER_LOCALE: ja_JP
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: password
      TZ: Asia/Tokyo
      MAIL_MAILER: smtp
      MAIL_HOST: mail
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: "null"
      QUEUE_CONNECTION: sync
      LANG: C.UTF-8
      LANGUAGE: en_US
      PHP_CS_FIXER_IGNORE_ENV: 1 # TODO php-cs-fixerがphp-8.4に対応した時点で削除

  database:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/default.cnf
    ports:
      - ${PORT_MYSQL:-0}:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  mail:
    image: axllent/mailpit
    ports:
      - ${PORT_WEB_MAIL:-8025}:8025

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8306:80
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  mysql:
  php:
