name: 'Tests'
on:
  push:

jobs:

  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build --no-cache
      - run: docker compose run php php -i

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: docker/php/
          file: docker/php/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: false
